name: GiftPost
main: com.Balor.bukkit.GiftPost.GiftPost
version: 1.0
author: Balor
license: GPLv3
description: >
            This plugin allow you to send item to a friend using a virtual chest.
commands:
 giftpost:
  description: master command
  aliases: gp
  usage: /<command>