name: GiftPost
main: com.Balor.bukkit.GiftPost.GiftPost
version: 1.0
author: Balor
description: >
            This plugin allow you to send item to a friend and if LWC is installed to a chest of a friend.
commands:
 gp_chest:
  description: Shows playes's chest
  aliases: chest
  usage: /<command>