name: VirtualChest
main: com.Balor.bukkit.GiftPost.GiftPost
version: 3.5
author: Balor
license: GPLv3
description: >
            This plugin allow you to send item to a friend using a virtual chest.
commands:
 giftpost:
  description: master command
  aliases: gp
  usage: /<command>
 partyChest:
  description: open the party chest (if mcMMO installed)
  aliases: pchest
  usage: /<command>